### ISSUE TITLE
pack_pipeline_e2e test is failing transiently

### ISSUE THREAD

**Issue by nirvedhmeshram** [nod-ai/iree-amd-aie#118]
Here is a gist showing the transient issue
https://gist.github.com/nirvedhmeshram/5deeaaa94729053794aa2dd9fbf223e0

**Comment by Abhishek-Varma** [comment]
[Prefetch lowering config before Packing and set later](https://github.com/nod-ai/iree-amd-aie/pull/125) solves this issue.

Reason for the failure -  the `lowering_config` was non-deterministically not being carried forward after the first application of `pack-and-transpose` and due to cascading effect `tile-and-fuse` couldn't perform tiling from 2nd level onwards.

CC: @MaheshRavishankar @nirvedhmeshram @yzhang93
